#!/usr/bin/env python
"""
postprocess.py : Compute Detection Probabilities and Optimization Metrics
=============================================================================

Usage
-----
    python postprocess.py --data-dir data
    python earthorbitplan/workflow/postprocess.py --config earthorbitplan/config/params_ultrasat.ini
"""

import argparse
import configparser
import logging
import sys
from pathlib import Path

import numpy as np
import synphot
from astropy import units as u
from astropy.coordinates import ICRS
from astropy.table import QTable
from astropy_healpix import HEALPix
from ligo.skymap.util.progress import progress_map
from m4opt import missions
from m4opt.synphot import observing
from m4opt.synphot.background import update_missions

from earthorbitplan.probability.detection_probability import (
    get_detection_probability_known_position,
)


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Post-process observation plans generated by M4OPT."
    )
    parser.add_argument("--config", type=str, help="Path to .ini configuration file")

    args, remaining_args = parser.parse_known_args()

    if args.config:
        config = configparser.ConfigParser()
        config.read(args.config)
        cfg = config["params"]
        return argparse.Namespace(
            data_dir=cfg.get("data_dir", fallback="data"),
            event_table=cfg.get("event_table", fallback="observing-scenarios.ecsv"),
            output_file=cfg.get("output_file", fallback="events.ecsv"),
            sched_dir=cfg.get("sched_dir", fallback="schedules"),
        )

    parser.add_argument("--data-dir", type=str, default="data")
    parser.add_argument("--event-table", type=str, default="observing-scenarios.ecsv")
    parser.add_argument("--output-file", type=str, default="events.ecsv")
    parser.add_argument("--sched-dir", type=str, default="schedules")

    return parser.parse_args(remaining_args)


def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
        force=True,
    )

def process(row, sched_path):
    """
    Process an event and extract detection probability, optimization metrics,
    and limiting magnitude.

    Parameters
    ----------
    row : astropy.table.Row
        Row containing event details.
    sched_path : pathlib.Path
        Path to the schedules directory.

    Returns
    -------
    tuple
        detection_probability_known_position, objective_value, best_bound,
        solution_status, solution_time, num_fields, limmag_best,
        cutoff, nside, mission, snr, deadline, delay,
        exptime_min, exptime_max, bandpass,
        absmag_mean, absmag_stdev, visits, skymap, skygrid.

        All values are None if the schedule file is missing.
    """
    run, event_id = row["run"], row["coinc_event_id"]
    plan_file = sched_path / run / f"{event_id}.ecsv"

    if not plan_file.exists():
        logging.warning(f"Missing schedule file: {plan_file}")
        return (None,) * 20

    plan      = QTable.read(plan_file)
    plan_args = plan.meta["args"]
    plan_args.pop("skymap", None)

    observations = plan[plan["action"] == "observe"].filled()
    num_fields   = len(observations) // plan_args["visits"]

    return (
        get_detection_probability_known_position(plan, row, plan_args),
        plan.meta.get("objective_value"),
        plan.meta.get("best_bound"),
        plan.meta.get("solution_status"),
        plan.meta.get("solution_time"),
        num_fields,
        plan_args.get("cutoff"),
        plan_args.get("nside"),
        plan_args.get("mission"),
        plan_args.get("snr"),
        plan_args.get("deadline"),
        plan_args.get("delay"),
        plan_args.get("exptime_min"),
        plan_args.get("exptime_max"),
        plan_args.get("bandpass"),
        plan_args.get("absmag_mean"),
        plan_args.get("absmag_stdev"),
        plan_args.get("visits"),
        plan_args.get("skymap"),
        plan_args.get("skygrid"),
    )


def main():
    args = parse_arguments()
    setup_logging()

    base_path   = Path(args.data_dir)
    input_path  = base_path / args.event_table
    sched_path  = base_path / args.sched_dir
    output_path = base_path / args.output_file

    logging.info(f"Loading event table from: {input_path}")
    table = QTable.read(input_path)

    logging.info("Computing detection probabilities and optimization metrics...")
    (
        table["detection_probability_known_position"],
        table["objective_value"],
        table["best_bound"],
        table["solution_status"],
        table["solution_time"],
        table["num_fields"],
        table["cutoff"],
        table["nside"],
        table["mission"],
        table["snr"],
        table["deadline"],
        table["delay"],
        table["exptime_min"],
        table["exptime_max"],
        table["bandpass"],
        table["absmag_mean"],
        table["absmag_stdev"],
        table["visits"],
        table["skymap"],
        table["skygrid"],
    ) = zip(*progress_map(lambda row: process(row, sched_path), table))

    logging.info(f"Saving results to: {output_path}")
    table.write(output_path, overwrite=True)


if __name__ == "__main__":
    main()
