#!/usr/bin/env python
"""
postprocess.py : Compute Detection Probabilities and Optimization Metrics
=============================================================================

Usage
-----
    python -m earthorbitplan.workflow.postprocess --data-dir data
    python src/earthorbitplan/workflow/postprocess.py --config src/earthorbitplan/config/params_ultrasat.ini
"""

import argparse
import configparser
import logging
import sys
from functools import partial
from pathlib import Path

import numpy as np
from astropy.table import QTable
from ligo.skymap.util.progress import progress_map

from earthorbitplan.probability.detection_probability import (
    get_detection_probability_known_position,
    observed_fields,
)


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Post-process observation plans generated by M4OPT."
    )
    parser.add_argument("--config", type=str, help="Path to .ini configuration file")

    args, remaining_args = parser.parse_known_args()

    if args.config:
        config = configparser.ConfigParser(inline_comment_prefixes=("#",))
        if not config.read(args.config):
            # configparser silently ignores an unreadable path, which would turn
            # every setting into a default and fail much later (or silently).
            parser.error(f"config file not found or unreadable: {args.config}")

        def get(
            key, fallback, sections=("paths", "postprocessing", "output", "params")
        ):
            """Read a key from the first section that defines it.

            The mission configs split settings across [paths] and
            [postprocessing] / [output]; params_scenarios.ini uses a flat
            [params] section.
            """
            for section in sections:
                v = config.get(section, key, fallback=None)
                if v is not None:
                    return v
            return fallback

        return argparse.Namespace(
            data_dir=get("data_dir", "data"),
            event_table=get("event_table", "observing-scenarios.ecsv"),
            output_file=get("output_file", "events.ecsv"),
            sched_dir=get("sched_dir", "schedules"),
        )

    parser.add_argument("--data-dir", type=str, default="data")
    parser.add_argument("--event-table", type=str, default="observing-scenarios.ecsv")
    parser.add_argument("--output-file", type=str, default="events.ecsv")
    parser.add_argument("--sched-dir", type=str, default="schedules")

    return parser.parse_args(remaining_args)


def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
        force=True,
    )


def process(row, sched_path):
    """
    Process an event and extract detection probability, optimization metrics,
    and limiting magnitude.

    Parameters
    ----------
    row : astropy.table.Row
        Row containing event details.
    sched_path : pathlib.Path
        Path to the schedules directory.

    Returns
    -------
    tuple
        detection_probability_known_position, objective_value, best_bound,
        solution_status, solution_time, num_fields, field_ids,
        cutoff, nside, mission, snr, deadline, delay,
        exptime_min, exptime_max, bandpass,
        absmag_mean, absmag_stdev, visits, skymap, skygrid.

        All values are None if the schedule file is missing.
    """
    run, event_id = row["run"], row["coinc_event_id"]
    plan_file = sched_path / run / f"{event_id}.ecsv"

    if not plan_file.exists():
        logging.warning(f"Missing schedule file: {plan_file}")
        # field_ids has to stay an array even when unknown: a None cannot be
        # written to the variable-length ECSV column.
        return (None,) * 6 + (np.array([], dtype=int),) + (None,) * 14

    plan = QTable.read(plan_file)
    plan_args = plan.meta["args"]
    plan_args.pop("skymap", None)

    observations = observed_fields(plan)
    if "field_id" in observations.colnames:
        # m4opt >= 2.13 names the sky grid tile of every observation, so the
        # fields can be counted directly instead of assuming that each one
        # received all of its visits -- an assumption that breaks on the plans
        # that stopped on "time limit exceeded".
        field_ids = np.unique(np.asarray(observations["field_id"]))
        num_fields = len(field_ids)
    else:
        # Schedules written before m4opt 2.13 carry no field_id.
        field_ids = np.array([], dtype=int)
        num_fields = len(observations) // plan_args["visits"]

    return (
        get_detection_probability_known_position(plan, row, plan_args),
        plan.meta.get("objective_value"),
        plan.meta.get("best_bound"),
        plan.meta.get("solution_status"),
        plan.meta.get("solution_time"),
        num_fields,
        field_ids,
        plan_args.get("cutoff"),
        plan_args.get("nside"),
        plan_args.get("mission"),
        plan_args.get("snr"),
        plan_args.get("deadline"),
        plan_args.get("delay"),
        plan_args.get("exptime_min"),
        plan_args.get("exptime_max"),
        plan_args.get("bandpass"),
        plan_args.get("absmag_mean"),
        plan_args.get("absmag_stdev"),
        plan_args.get("visits"),
        plan_args.get("skymap"),
        plan_args.get("skygrid"),
    )


def main():
    args = parse_arguments()
    setup_logging()

    base_path = Path(args.data_dir)
    input_path = base_path / args.event_table
    sched_path = base_path / args.sched_dir
    output_path = base_path / args.output_file

    logging.info(f"Loading event table from: {input_path}")
    table = QTable.read(input_path)

    logging.info("Computing detection probabilities and optimization metrics...")
    # progress_map ships the callable to worker processes through pickle, so it
    # cannot be a lambda or any other closure defined inside main().
    #
    # It pickles each item too, and an astropy Row keeps a reference to its
    # parent table: sending one row of this table costs 1.7 MB instead of the
    # 5 kB the row itself needs. Detaching each row into its own one-row table
    # first cuts the traffic ~340x and is what makes jobs=None worth using.
    rows = [table[i : i + 1][0] for i in range(len(table))]
    (
        table["detection_probability_known_position"],
        table["objective_value"],
        table["best_bound"],
        table["solution_status"],
        table["solution_time"],
        table["num_fields"],
        table["field_ids"],
        table["cutoff"],
        table["nside"],
        table["mission"],
        table["snr"],
        table["deadline"],
        table["delay"],
        table["exptime_min"],
        table["exptime_max"],
        table["bandpass"],
        table["absmag_mean"],
        table["absmag_stdev"],
        table["visits"],
        table["skymap"],
        table["skygrid"],
    ) = zip(*progress_map(partial(process, sched_path=sched_path), rows, jobs=None))

    logging.info(f"Saving results to: {output_path}")
    table.write(output_path, overwrite=True)


if __name__ == "__main__":
    main()
